# Exploratory Data Analysis : IBM 🤖🤖

In this exercise, you'll conduct an exploratory data analysis on a dataset from IBM, including information about the employees: age, income, education field, and attrition.

You'll be guided through different angles of analysis.

1. Import pandas and plotly express

In [1]:
import pandas as pd
import plotly.express as px

2. The dataset has 35 columns. Execute the cell below to avoid the columns to be truncated when displaying a table:

In [2]:
pd.options.display.max_columns = None

3. Read the file IBM_HR_ATTRITION.csv:

In [3]:
df = pd.read_csv("IBM_HR_ATTRITION.csv")
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2

4. Use one line of code to display various statistics about the dataset:

In [4]:
df.describe(include='all')

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470,1470,1470.000000,1470,1470.000000,1470.000000,1470,1470.0,1470.000000,1470.000000,1470,1470.000000,1470.000000,1470.000000,1470,1470.000000,1470,1470.000000,1470.000000,1470.000000,1470,1470,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
unique,NaN,2,3,NaN,3,NaN,NaN,6,NaN,NaN,NaN,2,NaN,NaN,NaN,9,NaN,3,NaN,NaN,NaN,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,No,Travel_Rarely,NaN,Research & Development,NaN,NaN,Life Sciences,NaN,NaN,NaN,Male,NaN,NaN,NaN,Sales Executive,NaN,Married,NaN,NaN,NaN,Y,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1233,1043,NaN,961,NaN,NaN,606,NaN,NaN,NaN,882,NaN,NaN,NaN,326,NaN,673,NaN,NaN,NaN,1470,1054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,36.923810,NaN,NaN,802.485714,NaN,9.192517,2.912925,NaN,1.0,1024.865306,2.721769,NaN,65.891156,2.729932,2.063946,NaN,2.728571,NaN,6502.931293,14313.103401,2.693197,NaN,NaN,15.209524,3.153741,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,NaN,NaN,403.509100,NaN,8.106864,1.024165,NaN,0.0,602.024335,1.093082,NaN,20.329428,0.711561,1.106940,NaN,1.102846,NaN,4707.956783,7117.786044,2.498009,NaN,NaN,3.659938,0.360824,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,NaN,NaN,102.000000,NaN,1.000000,1.000000,NaN,1.0,1.000000,1.000000,NaN,30.000000,1.000000,1.000000,NaN,1.000000,NaN,1009.000000,2094.000000,0.000000,NaN,NaN,11.000000,3.000000,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,NaN,NaN,465.000000,NaN,2.000000,2.000000,NaN,1.0,491.250000,2.000000,NaN,48.000000,2.000000,1.000000,NaN,2.000000,NaN,2911.000000,8047.000000,1.000000,NaN,NaN,12.000000,3.000000,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,NaN,NaN,802.000000,NaN,7.000000,3.000000,NaN,1.0,1020.500000,3.000000,NaN,66.000000,3.000000,2.000000,NaN,3.000000,NaN,4919.000000,14235.500000,2.000000,NaN,NaN,14.000000,3.000000,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,NaN,NaN,1157.000000,NaN,14.000000,4.000000,NaN,1.0,1555.750000,4.000000,NaN,83.750000,3.000000,3.000000,NaN,4.000000,NaN,8379.000000,20461.500000,4.000000,NaN,NaN,18.000000,3.000000,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,NaN,NaN,1499.000000,NaN,29.000000,5.000000,NaN,1.0,2068.000000,4.000000,NaN,100.000000,4.000000,5.000000,NaN,4.000000,NaN,19999.000000,26999.000000,9.000000,NaN,NaN,25.000000,4.000000,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

5. You can also use the `.info()` method to display some information about the data:

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

## Who are IBM's employees?
We'll first focus on very basic questions about age, gender, education level, etc...

6. How are the ages distributed?

In [6]:
fig = px.histogram(df, x = "Age")

# Définir une taille personnalisée
fig.update_layout(width=700, height=500)

fig.show()

7. Is the distribution of ages different for men and women?
Find two ways of investigating the difference

In [7]:
fig = px.histogram(df, x = "Age", color= "Gender")

# Définir une taille personnalisée
fig.update_layout(width=700, height=500)

fig.show()

In [8]:
fig = px.box(df, x = "Gender", y = "Age")

# Règler l'axe des y tous les 5 ans (au lieu de 10 sans).
fig.update_yaxes(dtick=5)   

# Définir une taille personnalisée
fig.update_layout(width=700, height=500)

fig.show()

8. What are the different education levels proportions?

In [9]:
education_level = df.groupby('Education').size().reset_index(name='Nombre')
    # size() compte toute les valeurs (NaN y compris), count() ne compte que les valeurs non nulles.
    # reset_index(name='Nombre') transforme la colonne d'index ('Education' en colonne) & nomme la colonne des résultats 'Nombre' ('0' si on ne mets pas name=)
education_level

   Education  Nombre
0          1     170
1          2     282
2          3     572
3          4     398
4          5      48

In [10]:
# px.pie?

In [11]:
fig = px.pie(education_level, names= "Education", values = "Nombre")

# Définir une taille personnalisée
fig.update_layout(width=700, height=500)

fig.show()

9. Same question for the education field?

In [12]:
education_field = df.groupby('EducationField').size().reset_index(name='Nombre')

education_field

     EducationField  Nombre
0   Human Resources      27
1     Life Sciences     606
2         Marketing     159
3           Medical     464
4             Other      82
5  Technical Degree     132

In [13]:
fig = px.pie(education_field, names= "EducationField", values = "Nombre")

# Définir une taille personnalisée
fig.update_layout(width=700, height=500)

fig.show()

10. What percentage of the employees never travel for business?

In [14]:
Business_Travel = df.groupby('BusinessTravel').size().reset_index(name='Nombre')

Business_Travel

      BusinessTravel  Nombre
0         Non-Travel     150
1  Travel_Frequently     277
2      Travel_Rarely    1043

In [15]:
fig = px.pie(Business_Travel, names= "BusinessTravel", values = "Nombre")

# Définir une taille personnalisée
fig.update_layout(width=700, height=500)

fig.show()

10. What's the percentage of women?

In [16]:
df_gender = df.groupby('Gender').size().reset_index(name='Nombre')

df_gender

   Gender  Nombre
0  Female     588
1    Male     882

In [17]:
fig = px.pie(df_gender, names= "Gender", values = "Nombre")

# Définir une taille personnalisée
fig.update_layout(width=700, height=500)

fig.show()

## Monthly Income
Let's investigate the employees monthly income.

11. As regards the income, is there equality between men and women?

In [18]:
fig = px.box(df, x = "Gender", y = "MonthlyIncome")

# Définir une taille personnalisée
fig.update_layout(width=700, height=500)

fig.show()

12. Is the income correlated to the employee's age?

In [19]:
fig = px.scatter(df, x = "Age", y = "MonthlyIncome")

# Définir une taille personnalisée
fig.update_layout(width=700, height=500)

fig.show()

In [20]:
fig = px.box(df, x = "MonthlyIncome", y = "Age", orientation="h")

# Définir une taille personnalisée
fig.update_layout(width=700, height=500)

fig.show()

13. Does the income depend on the education level?

In [21]:
fig = px.box(df, x = "Education", y = "MonthlyIncome")

# Définir une taille personnalisée
fig.update_layout(width=700, height=500)

fig.show()

The income depends a bit on the education level, especially for highest level (5) who tend to earn more money than others.

14. Does the monthly income depend on the employee's frequency of travel?

In [22]:
fig = px.box(df, x = "BusinessTravel", y = "MonthlyIncome")

# Définir une taille personnalisée
fig.update_layout(width=700, height=500)

fig.show()

15. What is the education field with the highest incomes in general?

In [23]:
fig = px.box(df, x = "EducationField", y = "MonthlyIncome")

# Définir une taille personnalisée
fig.update_layout(width=700, height=500)

fig.show()

## Attrition
Let's investigate the employees' attritions.

16. What percentage of the employees did quit their job?

In [24]:
df_attrition = df.groupby('Attrition').size().reset_index(name='Nombre')

df_attrition

  Attrition  Nombre
0        No    1233
1       Yes     237

In [25]:
fig = px.pie(df_attrition, names= "Attrition", values = "Nombre")

# Définir une taille personnalisée
fig.update_layout(width=700, height=500)

fig.show()

17. Could we anticipate an employee's attrition from his level of satisfaction in his job?

In [26]:
fig = px.box(df, x = "Attrition", y = "JobSatisfaction")

# Définir une taille personnalisée
fig.update_layout(width=700, height=500)

fig.show()

18. Is this different between men and women?

In [27]:
fig = px.box(df, x = "Attrition", y = "JobSatisfaction", color = 'Gender')

# Définir une taille personnalisée
fig.update_layout(width=700, height=500)

fig.show()

19. Now we would like to investigate the relationship between attrition and education field. We can't proceed like the previous analyses, as attrition and education field are both categorical variables! Let's do something else:
* Convert the Attrition column such that "Yes" is mapped to 1 and "No" is mapped to 0
* Then, compute the average of Attrition grouped by the education field
* Finally, plot the average attrition as a function of the education field.
* What is the education field with the highest attrition rate?

In [28]:
df['Attrition'] = df['Attrition'].apply(lambda x: 1 if x == "Yes" else 0)
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2

In [29]:
df_attrition_by_EducationField = df.groupby('EducationField')['Attrition'].mean().reset_index(name='Attrition')

df_attrition_by_EducationField

     EducationField  Attrition
0   Human Resources   0.259259
1     Life Sciences   0.146865
2         Marketing   0.220126
3           Medical   0.135776
4             Other   0.134146
5  Technical Degree   0.242424

In [30]:
fig = px.bar(df_attrition_by_EducationField, x = "EducationField", y = "Attrition")

# Définir une taille personnalisée
fig.update_layout(width=700, height=500)

fig.show()

The field with highest attrition rate is Human Resources